### ISSUE TITLE
Cookie options are not signed?

### ISSUE THREAD

**Issue by justreportingsomebug** [pillarjs/cookies#115]
I think only the key and value of the cookie are signed? Based on this line https://github.com/pillarjs/cookies/blob/master/index.js#L159

Does this mean that someone can change the other cookie options and the signature will not detect this?

I was wondering if I can just set a specific subdomain like `domain=www.example.com` to protect against [cross subdomain session fixation](https://en.wikipedia.org/wiki/Session_fixation#Attacks_using_cross-subdomain_cookie).

Example attack:
- an attacker gets a valid cookie and signature from me
- using an XSS on a subdomain, he can make a user set document.cookie to his cookie value by changing the domain on the cookie to the parent domain `domain=.example.com` (regardless of original value of httpOnly)
- user goes back to www.example.com. Because cookie options are not in the signature the cookie still valid.
- user logs in which also logs in the attacker.

Will this attack work?

**Comment by dougwilson** [comment]
The server has no way to know what the attributes are on the client, as the client only ever discloses the name and value to the server. So there is no method to possibly prevent the client from tampering with them, unfortunately. 

If you know of a way, please of course let us know and we can make a method to validate them.

**Comment by justreportingsomebug** [comment]
Thanks for the quick reply!

**Comment by dougwilson** [comment]
An interesting thought I had after I sent that: it would be nest if there was a method clients implemented that would prevent that from being possible. For example maybe a CSP directive to say "only x domains can set cookies for my domain" or something. I think generally the industry has moved to separate trusted and untrusted content by the top level domain due to the cookie setting issue, though. The wikipedia article you liked to also has a lot of good solutions, though those are scoped wider than what this module would do.

Probably the simplest method to defeat your description would be to set the HTTPOnly flag on the cookie so it wouldn't be readable in document.cookie (assuming that is how the attacker got it). You could also add additional validation data into the cookie value like source ip if you want to reject it if the request is coming from a different ip (since the user cannot alter the value without knowing your hmac secret key from the server).

I could probably help some more, but would need to better understand the exact scenario (step one seems pretty open and step four seems weird as to how a site would have two users logged in at the same time).

**Comment by justreportingsomebug** [comment]
Thanks! 

For step one, I might've phrased that confusingly. Attacker is just reading his own cookie so he can just use chrome inspector and httpOnly doesn't really help there.

For step four, the typical way to do authentication is to store server state saying that a session id (from the cookie) is logged in as some user. If the victim logs in with the attacker's session id, the attacker with the same cookie/session id will also be authenticated.

I will probably go with the standard solution such as resetting session id when logging in. This is a problem in the js ecosystem because [passport.js doesn't do it by default](https://github.com/jaredhanson/passport/issues/192).

Checking IP is also a really nice idea! Unfortunately IP tends to be unstable on mobile.

I might be curious to detect if these attacks are being attempted though. Is there a way to know if there are multiple cookie values with the same key? (i.e., set by a subdomain trying to overwrite parent domain)

**Comment by dougwilson** [comment]
> Is there a way to know if there are multiple cookie values with the same key?

Check the cookie header (res.headers.cookie) to see if there are multiple of the same cookie name. This is the only data about cookies the web browser sends to the server (it doesn't include the attribute values, thus why a module like this cannot validate the user has not tampered with them).
