### ISSUE TITLE
Cookies Having Independent Partitioned State (CHIPS, also know as Partitioned cookies)

### ISSUE THREAD

**Issue by yaverin** [pillarjs/cookies#151]
Hi! Please let me know, how can I set Partitioned flag for my cookies in NodeJS/Express application via "cookies" module?
Thanks in advance!

CHISP description:
- https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies
- https://developer.chrome.com/docs/privacy-sandbox/third-party-cookie-phase-out/#partitioned-cookies

**Comment by shoyuf** [comment]
I think this needs a pull request.

**Comment by matt-neal** [comment]
https://github.com/pillarjs/cookies/pull/152 PR created.

There is technically a way to work around the header not allowing `partitioned` by creating a utility file that overloads the `toHeader` function that adds the `if (this.partitioned ) header += '; partitioned';` bit. Obviously, the overloaded function is not tested and I cannot guarantee that it will work in the ways you need, but it is a possibility due to the way the library is built.
