### ISSUE TITLE
StirFry support

### ISSUE THREAD

**Issue by thesteeltoenail** [pillarjs/cookies#74]
Do you plan on adding support for StirFry? There are currently no cookie processors for it. I'm not completely sure how your code works, but you probably will be able to do it just by removing `next()`.

**Comment by dougwilson** [comment]
What is StirFry?

**Comment by thesteeltoenail** [comment]
It's a new web framework. http://stirfry-js.github.io/stirfry/

**Comment by dougwilson** [comment]
Ah, gotcha. So since I never head of it, I would not have had any plans to support it. Their docs don't tell me anything for how I am supposed to support it, either.

It shows request and response objects. Does your constructor not work?

    var cookies = new Cookies( request, response );

If not, I don't plan to learn it, but you can always make a pull request to add support, which is probably going to be the only way to proceed, especially with the lack of documentation for that framework.

**Comment by thesteeltoenail** [comment]
Ah, you can do it using `cookies(req.full, res.full)`

**Comment by dougwilson** [comment]
Oh, haha, I was just having `TypeError: res.getHeader is not a function` and was about to look into that when I got your response. Yea, now I can use it in their example:
```js
var Cookies = require('cookies');
var StirFry = require('stirfry');
var server  = new StirFry(8080);
server.request(function (request, response) {
    var cookies = new Cookies(request.full, response.full);
    cookies.set('foo', 'bar');
    response.send('Hello World!');
});
```
