### ISSUE TITLE
sha1 has been vulnerable to collisions for 12 years now

### ISSUE THREAD

**Issue by cmawhorter** [pillarjs/cookies#84]
I'm evaluating cookie modules for a project and noticed this one uses sha1 for signing, according to the readme.

From a look at Keygrip - it seems to default to sha256 these days.  Does that mean the README is out of date or a dep version bump is needed?

**Comment by dougwilson** [comment]
Sha1 has been vulnerable to collisions for years and years now, but I don't think within the size of a cookie value you can create to collisions, right? Can you link to the information on exactly the keyspace that is collidable?

**Comment by dougwilson** [comment]
Also, would be great if you wanted to put together a PR with the change you think would be the most appropriate to make to this module, thanks!

**Comment by dougwilson** [comment]
Hi @cmawhorter any interest in putting together that PR?

**Comment by cmawhorter** [comment]
I ended up going with a different lib so I'm probably not the best to PR here.  This was more a PSA.  

I don't think sha1 was susceptible to collisions until recently?  [This](https://arstechnica.com/security/2017/02/at-deaths-door-for-years-widely-used-sha1-function-is-now-dead/) is the most recent article I've read on the subject.

**Comment by dougwilson** [comment]
> I don't think sha1 was susceptible to collisions until recently?

Every hash function is susceptible to collisions. Just think about it: if every possible combination of bytes of all sizes can be represented in only a few bytes, clearly an infinite number of inputs will result in the same hash. The only thing that changed with SHA1 is that researchers spent thousands and thousands of computing hours eventually finding two things with the same hash. Nothing is broken with SHA1 and this shattered is just a publicity stunt yo push forward the browser agenda for certs to stop using sha1.

The keyspace of data that can fit into a cookie is not collidable, unless you have research that proves otherwise, which that article doesn't, as the two that collide are way bigger values than can fit in a cookie and contain binary values that cannot exist in a cookie.

Please provide the research that shows that sha1 is mot suitable to safely sign a cookie value.

**Comment by kevinburke** [comment]
> the two that collide are way bigger values than can fit in a cookie and contain binary values that cannot exist in a cookie.

I think you have to consider forward compatibility as well. SHA1 collision attacks are going to become more practical as GPU's get cheaper. 

If we want everyone to be protected 4 years from now we should probably upgrade the library's hash mechanism now.

**Comment by dougwilson** [comment]
With current GPUs and even CPUs you can already calculate every possible string that can fit in a cookie and none collide.

**Comment by dougwilson** [comment]
If you feel strongly about this, please put together a PR.

**Comment by cmawhorter** [comment]
i rediscovered this lib and searched for sha1 issues and shocked to find i posted this years ago. lol.

collisions aside, sha1 is now at the point that it is susceptible to brute forcing.  i'd wager a hefty sum of money that any nation state out there could break a sha1 signed cookie with a long lifespan these days.

and that's the core of the problem.  cookies typically have long lifespans.  if you're signing an api http request body that has a ~5m window of validity sha1 is still an ok choice.  but if you have 30/60/90+ days to brute force it then you're in for a world of hurt.

if you're still open to a pr i'd be happy to put one together.
