### ISSUE TITLE
Replacing Keygrip

### ISSUE THREAD

**Issue by elithrar** [pillarjs/cookies#86]
What is the appetite for replacing Keygrip, which seems to be struggling for support (https://github.com/crypto-utils/keygrip/pull/29), and building in straightforward signing directly into this library?

Specifically: making HMAC-SHA-256 the default via Node's [crypto.createHmac](https://nodejs.org/api/crypto.html#crypto_crypto_createhmac_algorithm_key), and supporting the option to provide your own `hashFunc(key, data)` if absolutely necessary.

If so, I'm happy to pull together a PR for this. I am one of the maintainers of gorilla/securecookie & gorilla/sessions (Go cookie libs) and this happens to be at the intersection of things I care about 🍪

**Comment by dougwilson** [comment]
Since we maintain Keygrip and this module, putting your efforts into Keygrip and then I merging the changes would be the same effort to directly embed into this module, no?

**Comment by elithrar** [comment]
I had considered that, but:

* Changing Keygrip would likely break Keygrip's API directly
* Keygrip, as it is, represents a very thin shim over crypto.createHmac, and will be thinner still once we cut ~30 lines and use https://nodejs.org/api/crypto.html#crypto_crypto_timingsafeequal_a_b and bury the ability to choose your own alg a layer deeper.
* Thus, the goal would be to limit the need for an additional dependency by calling out to createHmac directly. Signed cookies are definitely a core piece of this lib (and the secure web).

If you feel strongly about this, I'll review the changes to Keygrip. 

Outstanding questions:

* What is the appetite for ES6 syntax (thus raising the minimum Node version) in either this lib or Keygrip?
* Or TypeScript? (which could be compiled back down to ES5)

(Thanks for the quick reply)

**Comment by dougwilson** [comment]
I feel strongly that we should use Keygrip, and use this as the opportunity to improve Kegrip, to the benefit of this module and all other users of npm modules.

> What is the appetite for ES6 syntax (thus raising the minimum Node version) in either this lib or Keygrip?

Currently none; I would need a very, very good reason for an argument to use a minimum higher than Node.js 0.10, and certainly just fancy syntax is not a good enough reason. I take pride in supporting as far back as feasible, and there is no reason to drop versions just because the module's author(s) want to use fancy syntax; leave that for the end app developers.

> Or TypeScript? (which could be compiled back down to ES5)

Definitely zero.

**Comment by dougwilson** [comment]
And, that's not to say the burden is on you to figure out support in old versions you may not be familiar with -- I'm happy to help out on PRs as well, especially since GitHub allows by default repo collaborators to directly modify PRs, to make it more collaborative.

**Comment by elithrar** [comment]
OK, I'm convinced, especially since I just noticed that Koa also uses Keygrip, so the surface area seems much larger than the stars indicate :)

* I'll work on a proposal for Keygrip changes over the next week or so
* Get agreement
* <write code>
* Work to merge and cut a new version
* Submit a PR here to update the Keygrip version
* (at least) raise issues (if not PRs) on the largest "importers" of Keygrip and suggest they upgrade to the latest version. 

Does this approach work for you?

**Comment by dougwilson** [comment]
Yea, makes sense to me. It's also possible to depend on a git repo, so that means also a PR can be opened here against another GitHub repository even before an npm release to validate that everything is working together, if that's desired. I'm also open to a Skype / Hangout / similar if there is anything you want to hash out high-bandwidth.
